name: COM_Zombies
api-version: 1.13
main: com.zombies.COMZombies
authors: [Turkey2349&smeths]
description: Com Zombies Alpha
version: 1.2.8.0.1
load: POSTWORLD
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, CAPI, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag]
commands:
  zombies:
    description: Type /zombies help for more info!
    aliases: [z, zo, zom]
